### ISSUE TITLE
https requst

### ISSUE THREAD

**Issue by danial1964** [m57/ARDT#1]
hello i want to create https example request but i dont know how.can help me plz????

**Comment by m57** [comment]
It is just a standard request like:

GET /?val=%RANDOM% HTTP/1.1
Host: example.com
...
...
...

The "%RANDOM%" string is what will be substituted with random data to avoid cache hits on the edge nodes, resulting in the origin server being queried by Akamai.

**Comment by danial1964** [comment]
thanks for replay bro. i dont know why i take this error:   Response 'HTTP/1.0 400 Bad
my command is: python ARDT.py -t website.com -l ./akami-ips.txt -n 50 -r ./httpsexample.txt
my httpsexample is: 
GET /?val=%RANDOM% HTTP/1.1
Host: example.com
please help me bro

**Comment by m57** [comment]
Hey, no offense but i think you should try to do a bit more reading on this issue especially in the linked PDF (https://dl.packetstormsecurity.net/papers/attack/the_pentesters_guide_to_akamai.pdf) once you understand what this tool is doing you will be able to work it out for yourself. Thanks for the comments.
